### ISSUE TITLE
use ERROR_CORRECT_H data 2k qrcode.exceptions.DataOverflowError

### ISSUE THREAD

**Issue by hktalent** [lincolnloop/python-qrcode#176]
#174 #102 
```
Traceback (most recent call last):
  File "myqrcode.py", line 61, in <module>
    qr.make(fit=True)
  File "/usr/local/lib/python3.7/site-packages/qrcode/main.py", line 93, in make
    self.best_fit(start=self.version)
  File "/usr/local/lib/python3.7/site-packages/qrcode/main.py", line 165, in best_fit
    raise exceptions.DataOverflowError()
qrcode.exceptions.DataOverflowError
````

**Comment by hktalent** [comment]
@see https://blog.qr4.nl/page/QR-Code-Data-Capacity.aspx
