### ISSUE TITLE
Unable to create styled images

### ISSUE THREAD

**Issue by Sparkling-Phoenix** [lincolnloop/python-qrcode#275]
Hi! I'm using 7.3.1 with python 3.10.0 on a machine running Windows 10. I installed it using `pip install qrcode[pil]`

When I try to follow the example in the ReadMe 
```py
import qrcode
from qrcode.image.styledpil import StyledPilImage
from qrcode.image.styles.moduledrawers.pil import RoundedModuleDrawer
from qrcode.image.styles.colormasks import RadialGradiantColorMask

qr = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_L)
qr.add_data('Some data')

img_1 = qr.make_image(image_factory=StyledPilImage, module_drawer=RoundedModuleDrawer())
img_2 = qr.make_image(image_factory=StyledPilImage, color_mask=RadialGradiantColorMask())
img_3 = qr.make_image(image_factory=StyledPilImage, embeded_image_path="/path/to/image.png")
```

with my image, I get the following error 
```
Traceback (most recent call last):
  File "C:\Users\phnx\CustomFolder\somecode.py", line 6, in <module>
    from qrcode.image.styledpil import StyledPilImage
  File "C:\Users\phnx\AppData\Local\Programs\Python\Python310\lib\site-packages\qrcode\image\styledpil.py", line 14, in <module>    from qrcode.image.styles.moduledrawers import SquareModuleDrawer
ImportError: cannot import name 'SquareModuleDrawer' from 'qrcode.image.styles.moduledrawers' (C:\Users\phnx\AppData\Local\Programs\Python\Python310\lib\site-packages\qrcode\image\styles\moduledrawers\__init__.py)
```
I have gone back and checked that the things it is looking for are present and I have tried to uninstall and re-install this multiple times but I keep getting the same error. 

Could you please assist?

**Comment by Sparkling-Phoenix** [comment]
It seems to be an issue with my environment, I was asked to try to use a virtual environment and everything is working fine there. Closing this issue but leaving this here in case anyone else ever has this problem.
