### ISSUE TITLE
TypeError: Argument must be bytes or unicode, got 'bool'

### ISSUE THREAD

**Issue by jjakob** [lincolnloop/python-qrcode#333]
The code that calls qrcode is:
https://github.com/juga0/opgpcard/blob/47f62b1d6ceed1eeb58eeddaf2975a5910645a8b/opgpcard/qrsvg.py#L38

qrcode version 7.4.2
lxml version 4.9.2

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/opgpcard", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/opgpcard/cli.py", line 95, in main
    gen_opgpcard(args)
  File "/usr/lib/python3.11/site-packages/opgpcard/opgpcard.py", line 188, in gen_opgpcard
    qrsvg.gen_qr_svgimage(vcard, qr_path)
  File "/usr/lib/python3.11/site-packages/opgpcard/qrsvg.py", line 38, in gen_qr_svgimage
    img = qr.make_image(fit=True)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qrcode/main.py", line 365, in make_image
    im = image_factory(
         ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qrcode/image/svg.py", line 145, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/qrcode/image/svg.py", line 27, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/qrcode/image/base.py", line 139, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/qrcode/image/base.py", line 30, in __init__
    self._img = self.new_image(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qrcode/image/svg.py", line 63, in new_image
    return self._svg(**kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qrcode/image/svg.py", line 151, in _svg
    return super()._svg(viewBox=viewBox, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qrcode/image/svg.py", line 96, in _svg
    svg = super()._svg(tag=tag, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qrcode/image/svg.py", line 69, in _svg
    return ET.Element(
           ^^^^^^^^^^^
  File "src/lxml/etree.pyx", line 3042, in lxml.etree.Element
  File "src/lxml/apihelpers.pxi", line 131, in lxml.etree._makeElement
  File "src/lxml/apihelpers.pxi", line 119, in lxml.etree._makeElement
  File "src/lxml/apihelpers.pxi", line 318, in lxml.etree._initNodeAttributes
  File "src/lxml/apihelpers.pxi", line 335, in lxml.etree._addAttributeToNode
  File "src/lxml/apihelpers.pxi", line 1539, in lxml.etree._utf8
TypeError: Argument must be bytes or unicode, got 'bool'
```

**Comment by razvanioan** [comment]
having the same issue
was working fine in 7.3.1

**Comment by razvanioan** [comment]
For me it was in the override I had to do in order to easily allow custom foreground and background colors for SVG as well.

My initial code was this (which worked fine in v7.3.1)

```python
from qrcode import QRCode
from qrcode.image.svg import SvgPathImage

class MySvgPathImage(SvgPathImage):
    # override in order to support fill and back colors in SVG too
    def __init__(self, *args, **kw):
        self.background = kw.get('back_color')
        if fill := kw.get('fill_color'):
            self.QR_PATH_STYLE['fill'] = fill
        super().__init__(*args, **kw)
```

The error above appeared with newer versions of this module.

So I had to fix it like this:

```python
from qrcode import QRCode
from qrcode.image.svg import SvgPathImage

class MySvgPathImage(SvgPathImage):
    # override in order to support fill and back colors in SVG too
    def __init__(self, *args, **kw):
        self.background = kw.pop('back_color', None)
        self.QR_PATH_STYLE['fill'] = kw.pop('fill_color', '#000000')
        super().__init__(*args, **kw)
```

I have this as well on [SO here](https://stackoverflow.com/a/78877760/1529778) but where only the last version is presented (updated after the version bump)
