### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'Resampling'

### ISSUE THREAD

**Issue by justxi** [lincolnloop/python-qrcode#382]
Hello,

I'm trying to generate a QR-code on Windows 11, using python 3.12.3 and the qr-code library 7.4.2 (installed with pip).

I use the following code:

```
import qrcode
from qrcode.image.styledpil import StyledPilImage
from qrcode.image.styles.moduledrawers.pil import GappedSquareModuleDrawer

qr = qrcode.QRCode(version=1, box_size=40, border=0, error_correction=qrcode.constants.ERROR_CORRECT_L)
qr.add_data('https://www.github.com')

img_1 = qr.make_image(image_factory=StyledPilImage, module_drawer=GappedSquareModuleDrawer())
img_1.save("test-img1.png")
```

I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\user\Documents\dir\QRCode\test.py", line 12, in <module>
    img_1 = qr.make_image(image_factory=StyledPilImage, module_drawer=CircleModuleDrawer())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\qrcode\main.py", line 365, in make_image
    im = image_factory(
         ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\qrcode\image\styledpil.py", line 48, in __init__
    "embeded_image_resample", Image.Resampling.LANCZOS
                              ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Resampling'

```
On a Linux installation with with python 3.12.6 and qr-code library 7.4.2 ist works.

I appreciate any help or hints to solve this.

Thanks in advance.

**Comment by maribedran** [comment]
@justxi make sure you installed qrcode with the pil dependency. `pip install "qrcode[pil]"`

**Comment by justxi** [comment]
@maribedran Thanks, it works now.
