### ISSUE TITLE
Generation of image file fails with Python 3

### ISSUE THREAD

**Issue by Arfrever** [lincolnloop/python-qrcode#66]
Generation of image file with Python 3 triggers `TypeError: must be str, not bytes` exception:

```
$ PYTHONPATH="." python3.4 qrcode/console_scripts.py --help
Usage: qr - Convert stdin (or the first argument) to a QR Code.

When stdout is a tty the QR Code is printed to the terminal and when stdout is
a pipe to a file an image is written. The default image format is PNG.
...
$ PYTHONPATH="." python3.4 qrcode/console_scripts.py text
█████████████████████████████
█████████████████████████████
████ ▄▄▄▄▄ ███▄▄██ ▄▄▄▄▄ ████
████ █   █ █ ▀▄  █ █   █ ████
████ █▄▄▄█ █ ▄█▄ █ █▄▄▄█ ████
████▄▄▄▄▄▄▄█ █▄▀ █▄▄▄▄▄▄▄████
████ ▀▄ ▄ ▄██▄▀█ █▄ ▄  █▀████
████▄▀▄█ ▄▄▄▄█ ▄█▄█▀   ▄█████
█████▄██▄█▄▄ ▀▄ ▀ ▀█▄▄█ ▀████
████ ▄▄▄▄▄ █▀▀ ▀ ▀ ▄█▀ ▄█████
████ █   █ █  ▄█ ██ █ ▀▄█████
████ █▄▄▄█ █▄ ▄▄█▄█▀ █ ██████
████▄▄▄▄▄▄▄█▄▄█▄█▄██▄█▄▄█████
█████████████████████████████
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
$ PYTHONPATH="." python3.4 qrcode/console_scripts.py text > /tmp/image.png
Traceback (most recent call last):
  File "qrcode/console_scripts.py", line 65, in <module>
    main()
  File "qrcode/console_scripts.py", line 61, in main
    img.save(sys.stdout)
  File "/tmp/python-qrcode/qrcode/image/pil.py", line 32, in save
    self._img.save(stream, kind)
  File "/usr/lib64/python3.4/site-packages/PIL/Image.py", line 1685, in save
    save_handler(self, fp, filename)
  File "/usr/lib64/python3.4/site-packages/PIL/PngImagePlugin.py", line 631, in _save
    fp.write(_MAGIC)
TypeError: must be str, not bytes
```

Fix:

```
--- qrcode/console_scripts.py
+++ qrcode/console_scripts.py
@@ -58,7 +58,7 @@
         return

     img = qr.make_image(image_factory=image_factory)
-    img.save(sys.stdout)
+    img.save(sys.stdout.buffer if sys.version_info[0] >= 3 else sys.stdout)


 if __name__ == "__main__":
```

**Comment by ekevoo** [comment]
I am having the exact same problem in Mac OSX Yosemite. I see the fix assumes it is a Windows only problem…

**Comment by ekevoo** [comment]
Pillow-2.8.2-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl

**Comment by SmileyChris** [comment]
Are you using Python 3?

**Comment by ekevoo** [comment]
I seem to be. Can't tell for sure though, because /usr/bin/python is still 2. I always install stuff using pip3.

    ekevoo@anas:~$ python -V
    Python 2.7.6

    ekevoo@anas:~$ python3 -V
    Python 3.4.3

    ekevoo@anas:~$ qr aoeu > aoeu
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.4/bin/qr", line 9, in <module>
        load_entry_point('qrcode==5.1', 'console_scripts', 'qr')()
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/qrcode/console_scripts.py", line 60, in main
        img.save(sys.stdout)
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/qrcode/image/pil.py", line 32, in save
        self._img.save(stream, kind)
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PIL/Image.py", line 1693, in save
        save_handler(self, fp, filename)
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PIL/PngImagePlugin.py", line 686, in _save
        fp.write(_MAGIC)
    TypeError: must be str, not bytes

**Comment by SmileyChris** [comment]
Ah, the problem is I haven't rolled a release since fixing this(!)
It's on my short term todo list. Feel free to ping me in a few days if I haven't done it.

**Comment by ekevoo** [comment]
Awesome, thanks! :)

**Comment by ndevenish** [comment]
@SmileyChris ping? I just ran into this exact same issue pulling from Pypi...
