### ISSUE TITLE
Reading of first argument with non-UTF-8 characters fails with Python 3

### ISSUE THREAD

**Issue by Arfrever** [lincolnloop/python-qrcode#68]
Reading of first argument with non-UTF-8 characters with Python 3 triggers `UnicodeEncodeError` exception:

```
$ PYTHONPATH="." python3.4 qrcode/console_scripts.py $'\x80'
Traceback (most recent call last):
  File "qrcode/console_scripts.py", line 65, in <module>
    main()
  File "qrcode/console_scripts.py", line 52, in main
    qr.add_data(data)
  File "/tmp/python-qrcode/qrcode/main.py", line 58, in add_data
    self.data_list.extend(util.optimal_data_chunks(data))
  File "/tmp/python-qrcode/qrcode/util.py", line 315, in optimal_data_chunks
    data = to_bytestring(data)
  File "/tmp/python-qrcode/qrcode/util.py", line 354, in to_bytestring
    data = six.text_type(data).encode('utf-8')
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc80' in position 0: surrogates not allowed
```

First argument should be encoded with `surrogateescape` error handler, since surrogates are used in `sys.argv` for non-UTF-8 characters:

```
$ python3.4 -c 'import sys; print(sys.argv); print([x.encode(errors="surrogateescape") for x in sys.argv])' $'\x80'
['-c', '\udc80']
[b'-c', b'\x80']
```

Fix:

```
--- qrcode/console_scripts.py
+++ qrcode/console_scripts.py
@@ -46,6 +46,8 @@

     if args:
         data = args[0]
+        if sys.version_info[0] >= 3:
+            data = data.encode(errors="surrogateescape")
     else:
         data = (sys.stdin.buffer if sys.version_info[0] >= 3 else sys.stdin).read()
     if opts.optimize is None:
```

**Comment by welshjf** [comment]
After reading PEP 383, this looks OK to me.

**Comment by maribedran** [comment]
Fixed in https://github.com/lincolnloop/python-qrcode/commit/1285c6d20feaaccee8f87959f6e7a17d41722dbe
