### ISSUE TITLE
qr command line tool throw exception with python-2.6.6

### ISSUE THREAD

**Issue by tangxinfa** [lincolnloop/python-qrcode#79]
# qr hello
    Traceback (most recent call last):
      File "/usr/bin/qr", line 9, in <module>
        load_entry_point('qrcode==5.1', 'console_scripts', 'qr')()
      File "/usr/lib/python2.6/site-packages/qrcode-5.1-py2.6.egg/qrcode/console_scripts.py", line 56, in main
        qr.print_ascii(tty=True)
      File "/usr/lib/python2.6/site-packages/qrcode-5.1-py2.6.egg/qrcode/main.py", line 235, in print_ascii
        out.write(codes[pos])
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u2588' in position 0: ordinal not in range(128)

Modify  "out.write(codes[pos])" to "out.write(codes[pos].encode('utf-8'))" fixed this problem.

**Comment by welshjf** [comment]
Suggested fix will not work on Python 3 (stdout isn't binary) or Windows (console isn't UTF-8). This one should work.

**Comment by welshjf** [comment]
Chris, did you note my comment above? This conversion of everything to bytes broke python 3:

````
Traceback (most recent call last):
  File "/home/jwelsh/.local/bin/qr", line 9, in <module>
    load_entry_point('qrcode==5.2.1.post0', 'console_scripts', 'qr')()
  File "/home/jwelsh/foss/welshjf/python-qrcode/qrcode/console_scripts.py", line 73, in main
    qr.print_ascii(tty=True)
  File "/home/jwelsh/foss/welshjf/python-qrcode/qrcode/main.py", line 231, in print_ascii
    out.write(b'\x1b[48;5;232m')   # Background black
TypeError: must be str, not bytes
````

And I'd guess Windows console too since it's not UTF-8.

**Comment by SmileyChris** [comment]
Derp. On it...
