### ISSUE TITLE
MemoryError with negative box_size

### ISSUE THREAD

**Issue by Zockermike** [lincolnloop/python-qrcode#94]
Traceback (most recent call last):
  File "/home/michi/Python/qrcodetests.py", line 13, in <module>
    img = qr.make_image()
  File "build/bdist.linux-x86_64/egg/qrcode/main.py", line 267, in make_image
  File "build/bdist.linux-x86_64/egg/qrcode/image/base.py", line 13, in __init__
  File "build/bdist.linux-x86_64/egg/qrcode/image/pil.py", line 33, in new_image
  File "build/bdist.linux-x86_64/egg/PIL/Image.py", line 2022, in new
MemoryError

==================================================================

Testscript:
import qrcode
from PIL import Image

qr = qrcode.QRCode(
    version=1,
    error_correction=qrcode.constants.ERROR_CORRECT_H,
    box_size=-100,
    border=20,
)
qr.add_data('vielzulangerstring')
qr.make(fit=True)
img = qr.make_image()

==================================================================

Negative box_size should throw something like "Invalid Parameter Exception" instead of "MemoryError"

**Comment by SmileyChris** [comment]
Probably should, but it's definitely in the "then don't do that" category :)
If you want to work on it, I'll merge it.
