### ISSUE TITLE
Requirement PIL/Pillow missing in setup.py

### ISSUE THREAD

**Issue by htgoebel** [lincolnloop/python-qrcode#95]
The requirement for PIL respective Pillow is missing, see below.

Name: qrcode
Version: 5.2.2
```
$ virtualenv foo
$ . foo/bin/activate
(foo) $ pip install qrcode
(foo) $ qr </tmp/x.txt > /tmp/x.png
Traceback (most recent call last):
  File "/tmp/foo/bin/qr", line 11, in <module>
    sys.exit(main())
  File "/tmp/foo/lib/python2.7/site-packages/qrcode/console_scripts.py", line 80, in main
    img = qr.make_image(image_factory=image_factory)
  File "/tmp/foo/lib/python2.7/site-packages/qrcode/main.py", line 263, in make_image
    from qrcode.image.pil import PilImage
  File "/tmp/foo/lib/python2.7/site-packages/qrcode/image/pil.py", line 8, in <module>
    import Image
ImportError: No module named Image
```

**Comment by SmileyChris** [comment]
It's because qrcode works without it if you use an alternate factory (or just generate console qr codes), so I didn't want to make it an explicit requirement. Thanks for the report though
